name: Build with Makefile

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Initialize and Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Make configure.sh executable
        run: chmod +x configure.sh
      - name: Configure
        run: ./configure.sh -c
      - name: Build
        run: make
